version: 2

# Source definitions moved to models/sources.yml
# This file contains model-level tests only

models:
  - name: stg_accounts
    description: Cleaned accounts — TEST and DEMO excluded.
    columns:
      - name: account_id
        tests:
          - unique
          - not_null

  - name: stg_subscriptions
    description: >
      Cleaned subscriptions joined to stg_accounts.
      Adds is_plan_change_end flag.
    columns:
      - name: subscription_id
        tests:
          - unique
          - not_null
      - name: account_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_accounts')
              field: account_id
      - name: status
        tests:
          - accepted_values:
              values: ['active', 'cancelled', 'paused']
      - name: is_plan_change_end
        tests:
          - not_null
          - accepted_values:
              values: [true, false]

  - name: stg_plans
    description: Plan reference data.
    columns:
      - name: plan_id
        tests:
          - unique
          - not_null
      - name: billing_cycle
        tests:
          - accepted_values:
              values: ['monthly', 'annual']

  - name: mart_monthly_churn
    description: Monthly churn rate — rolling 12 months.
    columns:
      - name: cohort_month
        tests:
          - unique
          - not_null
      - name: churn_rate_pct
        tests:
          - not_null

  - name: mart_churn_by_plan
    description: Churn by plan tier + billing cycle — rolling 6 months.
    columns:
      - name: logo_churn_rate_pct
        tests:
          - not_null
      - name: mrr_churn_rate_pct
        tests:
          - not_null

  - name: mart_first_vs_rechurn
    description: First-churn vs re-churn — rolling 12 months.
    columns:
      - name: churn_type
        tests:
          - unique
          - not_null
          - accepted_values:
              values: ['first_churn', 're_churn']

  - name: mart_subscription_overlaps
    description: Data quality — overlapping subscription pairs.
